from dataclasses import asdict, dataclass


@dataclass
class OZONColumnsDTO:
    ozon_id: str = 'OZON ID'
    ozon_article: str = 'Артикул OZON'
    seller_article: str = 'Артикул продавца'
    barcode: str = 'Баркод'
    brand: str = 'Бренд'
    category: str = 'Тип'
    collection: str = 'Коллекция'
    name: str = 'Название предмета'
    fbs_stocks: str = 'Остатки FBS'
    fbs_reserv: str = 'Зарезервировано FBS'
    fbo_stocks: str = 'Остатки FBO'
    fbo_reserv: str = 'Зарезервировано FBO'
    in_way_to_client: str = 'В пути к клиенту'
    in_way_from_client: str = 'В пути от клиента'
    price_without_discount: str = '(OZON) Цена без скидки (Зачеркнутая)'
    seller_discount: str = '(OZON) Скидка продавца'
    price_with_seller_discount: str = '(OZON) Цена со скидкой продавца'
    ozon_discount: str = 'Скидка OZON'
    price_with_ozon_discount: str = '(OZON) Цена со скидкой озон (Черная)'
    price_with_ozon_club: str = '(OZON) Цена с озон картой (Зеленая)'
    med_price_without_discount: str = '(MED) Цена без скидки'
    med_discount: str = '(MED) Скидка продавца'
    med_price_with_discount: str = '(MED) Цена со скидкой продавца'
    price_difference: str = 'Разность цен ●'
    equilibrium_discount: str = 'Скидка для равновесия'
    status: str = 'Статус товара'
    equilibrium_price: str = 'Цена для равновесия'
    purchase: str = 'Закупка'